version: "3"
services:

  api:
    build:
      context: ./backend
    environment:
      STORAGE: mysql
      MYSQL_HOST: db
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PWD: "${MYSQL_PWD}"
      MYSQL_DB: "${MYSQL_DB}"


  frontend:
    image: nginx:1.22
    volumes:
      - "./frontend:/var/www/static:ro"
      - "./frontend/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PWD}"
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: 
      MYSQL_PASSWORD: "${MYSQL_PWD}"
    volumes:
      - "db-volume:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"

volumes:
  db-volume:



